server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://db:5432/rinha
    #url: jdbc:postgresql://localhost:5432/rinha
    driverClassName: org.postgresql.Driver
    #username: postgres
    #password: Neves123
    username: admin
    password: 123
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
